title: de·centrum
baseURL: https://decentrum.cz/
enableRobotsTXT: true

params:
  description: "de·centrum je web o praktické soběstačnosti v komplexním světě, stojící na pilířích technologií, financí, praktických dovedností a zdraví."
  twitterHandle: "@decentrumcz"
  twitterUrl: https://twitter.com/decentrumcz
  email: info@decentrum.cz

permalinks:
  archiv: /:filename/

defaultContentLanguage: cs
disableKinds:
  - taxonomy
  - taxonomyTerm
disableHugoGeneratorInject: true

markup:
  goldmark:
    renderer:
      unsafe: true
    parser:
      autoHeadingIDType: github-ascii