title: de·centrum
baseURL: https://decentrum.cz/
enableRobotsTXT: true

timeout: 30s

params:
  description: "de·centrum je web o praktické soběstačnosti v komplexním světě, stojící na pilířích technologií, financí, praktických dovedností a zdraví."
  shortDescription: "praktická soběstačnost v komplexním světě"
  twitterHandle: "@decentrumcz"
  twitterUrl: https://twitter.com/decentrumcz
  email: info@decentrum.cz

permalinks:
  blog: /:filename/
  categories: /archiv/:slug

defaultContentLanguage: cs
disableKinds:
  - taxonomyTerm
disableHugoGeneratorInject: true

outputs:
  home:
    - HTML
    - RSS
    - JSON
  section:
    - HTML
  taxonomy:
    - HTML

outputFormats:
  JSON:
    baseName: manifest

taxonomies:
  category: categories

markup:
  goldmark:
    renderer:
      unsafe: true
    parser:
      autoHeadingIDType: github-ascii